export enum STATUS_CODE {
  SUCCESS = 200,
  BAD_REQUEST = 400,
  AUTH_FAILURE = 401,
  NOT_FOUND = 404,
  SERVER_ERROR = 500,
}

const highways = [
  {
    route_id: "0010",
    route_name: "경부고속도로",
    start_point: "서울",
    end_point: "부산",
    distance: 416050,
  },
];
const routeInfo = {
  route_id: "0010",
  route_name: "경부고속도로",
  start_point: "부산",
  end_point: "서울",
  updated_at: "timestamp",
  directions: {
    forward: {
      sections: [
        {
          section_id: "string",
          start_name: "한남IC",
          end_name: "잠원IC",
          distance: 1500,
          order_num: 1,
          status: "CONGESTED",
          travel_time: 115,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "잠원IC",
          end_name: "반포IC",
          distance: 1200,
          order_num: 1,
          status: "SLOW",
          travel_time: 333,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "반포IC",
          end_name: "서초IC",
          distance: 2300,
          order_num: 1,
          status: "SLOW",
          travel_time: 187,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "서초IC",
          end_name: "양재IC",
          distance: 2500,
          order_num: 1,
          status: "CONGESTED",
          travel_time: 171,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "양재IC",
          end_name: "만남의광장교차로",
          distance: 778,
          order_num: 1,
          status: "SMOOTH",
          travel_time: 59,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "만남의광장교차로",
          end_name: "상적교",
          distance: 2500,
          order_num: 1,
          status: "SMOOTH",
          travel_time: 161,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "상적교",
          end_name: "대왕판교IC",
          distance: 2500,
          order_num: 1,
          status: "SMOOTH",
          travel_time: 107,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "대왕판교IC",
          end_name: "판교JC",
          distance: 937,
          order_num: 1,
          status: "SMOOTH",
          travel_time: 59,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "판교JC",
          end_name: "판교IC",
          distance: 1300,
          order_num: 1,
          status: "SMOOTH",
          travel_time: 59,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "판교IC",
          end_name: "서울톨게이트",
          distance: 3100,
          order_num: 1,
          status: "SMOOTH",
          travel_time: 130,
          speed: "number",
        },
      ],
    },
    reverse: {
      sections: [
        {
          section_id: "string",
          start_name: "잠원IC",
          end_name: "한남IC",
          distance: 1500,
          order_num: 1,
          status: "CONGESTED",
          travel_time: 78,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "반포IC",
          end_name: "잠원IC",
          distance: 1200,
          order_num: 1,
          status: "SLOW",
          travel_time: 60,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "서초IC",
          end_name: "반포IC",
          distance: 2300,
          order_num: 1,
          status: "SLOW",
          travel_time: 204,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "양재IC",
          end_name: "서초IC",
          distance: 2500,
          order_num: 1,
          status: "CONGESTED",
          travel_time: 780,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "만남의광장교차로",
          end_name: "양재IC",
          distance: 778,
          order_num: 1,
          status: "SMOOTH",
          travel_time: 177,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "상적교",
          end_name: "만남의광장교차로",
          distance: 2500,
          order_num: 1,
          status: "SMOOTH",
          travel_time: 139,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "대왕판교IC",
          end_name: "상적교",
          distance: 2500,
          order_num: 1,
          status: "SMOOTH",
          travel_time: 99,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "판교JC",
          end_name: "대왕판교IC",
          distance: 937,
          order_num: 1,
          status: "SMOOTH",
          travel_time: 64,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "판교IC",
          end_name: "판교JC",
          distance: 1300,
          order_num: 1,
          status: "CONGESTED",
          travel_time: 249,
          speed: "number",
        },
        {
          section_id: "string",
          start_name: "서울톨게이트",
          end_name: "판교IC",
          distance: 3100,
          order_num: 1,
          status: "CONGESTED",
          travel_time: 780,
          speed: "number",
        },
      ],
    },
  },
};

export { highways, routeInfo };
