const sections = [
  {
    name: "한남IC",
    distance: "7.4",
    leftStatus: "서행",
    leftTime: "15",
    rightStatus: "서행",
    rightTime: "13",
  },
  {
    name: "양재IC",
    distance: "12.4",
    leftStatus: "원활",
    leftTime: "8",
    rightStatus: "서행",
    rightTime: "32",
  },
  {
    name: "서울톨게이트",
    distance: "16.6",
    leftStatus: "원활",
    leftTime: "12",
    rightStatus: "원활",
    rightTime: "17",
  },
  {
    name: "기흥동탄IC",
    distance: "23.1",
    leftStatus: "원활",
    leftTime: "17",
    rightStatus: "원활",
    rightTime: "15",
  },
  {
    name: "안성JC",
    distance: "29.2",
    leftStatus: "원활",
    leftTime: "20",
    rightStatus: "원활",
    rightTime: "19",
  },
  {
    name: "천안JC",
    distance: "34.5",
    leftStatus: "원활",
    leftTime: "22",
    rightStatus: "원활",
    rightTime: "22",
  },
  {
    name: "남이JC",
    distance: "21.5",
    leftStatus: "원활",
    leftTime: "14",
    rightStatus: "원활",
    rightTime: "14",
  },
  {
    name: "회덕JC",
    distance: "9.7",
    leftStatus: "원활",
    leftTime: "7",
    rightStatus: "원활",
    rightTime: "6",
  },
  {
    name: "비룡JC",
    distance: "36.4",
    leftStatus: "원활",
    leftTime: "22",
    rightStatus: "원활",
    rightTime: "23",
  },
  {
    name: "영동IC",
    distance: "48.5",
    leftStatus: "원활",
    leftTime: "28",
    rightStatus: "원활",
    rightTime: "30",
  },
  {
    name: "김천JC",
    distance: "40.7",
    leftStatus: "원활",
    leftTime: "25",
    rightStatus: "원활",
    rightTime: "25",
  },
  {
    name: "오산교",
    distance: "19.9",
    leftStatus: "원활",
    leftTime: "13",
    rightStatus: "원활",
    rightTime: "13",
  },
  {
    name: "동대구JC",
    distance: "26.4",
    leftStatus: "원활",
    leftTime: "15",
    rightStatus: "원활",
    rightTime: "16",
  },
  {
    name: "영천IC",
    distance: "28.0",
    leftStatus: "원활",
    leftTime: "16",
    rightStatus: "원활",
    rightTime: "17",
  },
  {
    name: "경주IC",
    distance: "28.4",
    leftStatus: "원활",
    leftTime: "17",
    rightStatus: "원활",
    rightTime: "18",
  },
  {
    name: "언양JC",
    distance: "26.5",
    leftStatus: "원활",
    leftTime: "17",
    rightStatus: "원활",
    rightTime: "16",
  },
  {
    name: "양산JC",
    distance: "13.3",
    leftStatus: "원활",
    leftTime: "10",
    rightStatus: "원활",
    rightTime: "9",
  },
  {
    name: "만남의광장",
    isLast: true,
    leftStatus: "원활",
    rightStatus: "원활",
  },
];

export { sections };
